language: ruby
rvm:
- 2.0.0
branches:
  only:
  - source
script: bundle exec rake travis
env:
  global:
  - secure: "JG7DbjScAPOip2m8M8x7mikHa4SaNZ8mmjRQfvg58J1zLlkr6L+DCZqG5zB9mypBeQ0gvpUOTNBTEJtd3W1vWIV1tPzQqaPYJJGuH4lioZ7RxMNYR5Ja1W/ocP9yEWyuPVdDqowJnws5F0pS1nox89OfVZR5LTXvbWJaZMsMWjk="