language: ruby
rvm:
- 2.0.0
branches:
  only:
  - source
script: bundle exec rake travis
env:
  global:
  - secure: "hL1B9hneYCQczIOnv9vSTw/upuvsnO/UyY6kMezPZg7ZM28oCKVtiuKM0a8VPbkMJAIrfFIgh5z4JHRZS6JhzMufQYfRg0fZUqBPHLOfdU8MFNN0WkDTTRXJKFpDrkzKeLvjyqnevJriDGBq95r8QVC+5tXe1YuLcaz64S1qoNs="