language: ruby
rvm:
- 2.0.0
branches:
  only:
  - source
script: bundle exec rake travis
env:
  global:
  - secure: "j+R+Ajp+KruPYL03p04FJveCTCZ6WD7c3HVsY0ROCGj33p7DRDDIYzSXuAsKKryf08zWxaYdp8/5JcnFKwy4hNX0I51jA2H9N1qvgsgt3n8Tj3l+PORibWZtZhfdX1gTiKW25CraMb8g+VXgj0DVLJx+SBz3rJb31GWFl08lJfg="
